/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CourtsRouteImport } from './routes/courts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCourtIdRouteImport } from './routes/c.$courtId'
import { Route as CCourtIdPrintRouteImport } from './routes/c.$courtId.print'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsRoute = CourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCourtIdRoute = CCourtIdRouteImport.update({
  id: '/c/$courtId',
  path: '/c/$courtId',
  getParentRoute: () => rootRouteImport,
} as any)
const CCourtIdPrintRoute = CCourtIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => CCourtIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courts': typeof CourtsRoute
  '/register': typeof RegisterRoute
  '/c/$courtId': typeof CCourtIdRouteWithChildren
  '/c/$courtId/print': typeof CCourtIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courts': typeof CourtsRoute
  '/register': typeof RegisterRoute
  '/c/$courtId': typeof CCourtIdRouteWithChildren
  '/c/$courtId/print': typeof CCourtIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courts': typeof CourtsRoute
  '/register': typeof RegisterRoute
  '/c/$courtId': typeof CCourtIdRouteWithChildren
  '/c/$courtId/print': typeof CCourtIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courts' | '/register' | '/c/$courtId' | '/c/$courtId/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courts' | '/register' | '/c/$courtId' | '/c/$courtId/print'
  id:
    | '__root__'
    | '/'
    | '/courts'
    | '/register'
    | '/c/$courtId'
    | '/c/$courtId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourtsRoute: typeof CourtsRoute
  RegisterRoute: typeof RegisterRoute
  CCourtIdRoute: typeof CCourtIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts': {
      id: '/courts'
      path: '/courts'
      fullPath: '/courts'
      preLoaderRoute: typeof CourtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$courtId': {
      id: '/c/$courtId'
      path: '/c/$courtId'
      fullPath: '/c/$courtId'
      preLoaderRoute: typeof CCourtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$courtId/print': {
      id: '/c/$courtId/print'
      path: '/print'
      fullPath: '/c/$courtId/print'
      preLoaderRoute: typeof CCourtIdPrintRouteImport
      parentRoute: typeof CCourtIdRoute
    }
  }
}

interface CCourtIdRouteChildren {
  CCourtIdPrintRoute: typeof CCourtIdPrintRoute
}

const CCourtIdRouteChildren: CCourtIdRouteChildren = {
  CCourtIdPrintRoute: CCourtIdPrintRoute,
}

const CCourtIdRouteWithChildren = CCourtIdRoute._addFileChildren(
  CCourtIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourtsRoute: CourtsRoute,
  RegisterRoute: RegisterRoute,
  CCourtIdRoute: CCourtIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
